/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package hardware.pelicano;

public class CoinPolling_t {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CoinPolling_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CoinPolling_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(CoinPolling_t obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        PelicanoControlJNI.delete_CoinPolling_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setChannel(int value) {
    PelicanoControlJNI.CoinPolling_t_Channel_set(swigCPtr, this, value);
  }

  public int getChannel() {
    return PelicanoControlJNI.CoinPolling_t_Channel_get(swigCPtr, this);
  }

  public void setCoin(int value) {
    PelicanoControlJNI.CoinPolling_t_Coin_set(swigCPtr, this, value);
  }

  public int getCoin() {
    return PelicanoControlJNI.CoinPolling_t_Coin_get(swigCPtr, this);
  }

  public CoinPolling_t() {
    this(PelicanoControlJNI.new_CoinPolling_t(), true);
  }

}
