/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package hardware.pelicano;

public class GlobalVariables {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected GlobalVariables(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GlobalVariables obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(GlobalVariables obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        PelicanoControlJNI.delete_GlobalVariables(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setPelicanoObject(PelicanoClass value) {
    PelicanoControlJNI.GlobalVariables_PelicanoObject_set(swigCPtr, this, PelicanoClass.getCPtr(value), value);
  }

  public PelicanoClass getPelicanoObject() {
    long cPtr = PelicanoControlJNI.GlobalVariables_PelicanoObject_get(swigCPtr, this);
    return (cPtr == 0) ? null : new PelicanoClass(cPtr, false);
  }

  public void setPelicanoPointer(PelicanoClass value) {
    PelicanoControlJNI.GlobalVariables_PelicanoPointer_set(swigCPtr, this, PelicanoClass.getCPtr(value), value);
  }

  public PelicanoClass getPelicanoPointer() {
    long cPtr = PelicanoControlJNI.GlobalVariables_PelicanoPointer_get(swigCPtr, this);
    return (cPtr == 0) ? null : new PelicanoClass(cPtr, false);
  }

  public void setSMObject(SMClass value) {
    PelicanoControlJNI.GlobalVariables_SMObject_set(swigCPtr, this, SMClass.getCPtr(value), value);
  }

  public SMClass getSMObject() {
    long cPtr = PelicanoControlJNI.GlobalVariables_SMObject_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SMClass(cPtr, false);
  }

  public GlobalVariables() {
    this(PelicanoControlJNI.new_GlobalVariables(), true);
  }

}
