/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package hardware.pelicano;

public class PelicanoClass {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected PelicanoClass(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PelicanoClass obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(PelicanoClass obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        PelicanoControlJNI.delete_PelicanoClass(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setSerialPort(int value) {
    PelicanoControlJNI.PelicanoClass_SerialPort_set(swigCPtr, this, value);
  }

  public int getSerialPort() {
    return PelicanoControlJNI.PelicanoClass_SerialPort_get(swigCPtr, this);
  }

  public void setSuccessConnect(boolean value) {
    PelicanoControlJNI.PelicanoClass_SuccessConnect_set(swigCPtr, this, value);
  }

  public boolean getSuccessConnect() {
    return PelicanoControlJNI.PelicanoClass_SuccessConnect_get(swigCPtr, this);
  }

  public void setPortO(int value) {
    PelicanoControlJNI.PelicanoClass_PortO_set(swigCPtr, this, value);
  }

  public int getPortO() {
    return PelicanoControlJNI.PelicanoClass_PortO_get(swigCPtr, this);
  }

  public void setCoinEvent(int value) {
    PelicanoControlJNI.PelicanoClass_CoinEvent_set(swigCPtr, this, value);
  }

  public int getCoinEvent() {
    return PelicanoControlJNI.PelicanoClass_CoinEvent_get(swigCPtr, this);
  }

  public void setCoinEventPrev(int value) {
    PelicanoControlJNI.PelicanoClass_CoinEventPrev_set(swigCPtr, this, value);
  }

  public int getCoinEventPrev() {
    return PelicanoControlJNI.PelicanoClass_CoinEventPrev_get(swigCPtr, this);
  }

  public void setCoinCinc(int value) {
    PelicanoControlJNI.PelicanoClass_CoinCinc_set(swigCPtr, this, value);
  }

  public int getCoinCinc() {
    return PelicanoControlJNI.PelicanoClass_CoinCinc_get(swigCPtr, this);
  }

  public void setCoinCien(int value) {
    PelicanoControlJNI.PelicanoClass_CoinCien_set(swigCPtr, this, value);
  }

  public int getCoinCien() {
    return PelicanoControlJNI.PelicanoClass_CoinCien_get(swigCPtr, this);
  }

  public void setCoinDosc(int value) {
    PelicanoControlJNI.PelicanoClass_CoinDosc_set(swigCPtr, this, value);
  }

  public int getCoinDosc() {
    return PelicanoControlJNI.PelicanoClass_CoinDosc_get(swigCPtr, this);
  }

  public void setCoinQuin(int value) {
    PelicanoControlJNI.PelicanoClass_CoinQuin_set(swigCPtr, this, value);
  }

  public int getCoinQuin() {
    return PelicanoControlJNI.PelicanoClass_CoinQuin_get(swigCPtr, this);
  }

  public void setCoinMil(int value) {
    PelicanoControlJNI.PelicanoClass_CoinMil_set(swigCPtr, this, value);
  }

  public int getCoinMil() {
    return PelicanoControlJNI.PelicanoClass_CoinMil_get(swigCPtr, this);
  }

  public void setErrorHappened(boolean value) {
    PelicanoControlJNI.PelicanoClass_ErrorHappened_set(swigCPtr, this, value);
  }

  public boolean getErrorHappened() {
    return PelicanoControlJNI.PelicanoClass_ErrorHappened_get(swigCPtr, this);
  }

  public void setCriticalError(boolean value) {
    PelicanoControlJNI.PelicanoClass_CriticalError_set(swigCPtr, this, value);
  }

  public boolean getCriticalError() {
    return PelicanoControlJNI.PelicanoClass_CriticalError_get(swigCPtr, this);
  }

  public void setErrorSolved(boolean value) {
    PelicanoControlJNI.PelicanoClass_ErrorSolved_set(swigCPtr, this, value);
  }

  public boolean getErrorSolved() {
    return PelicanoControlJNI.PelicanoClass_ErrorSolved_get(swigCPtr, this);
  }

  public void setErrorNoSolved(boolean value) {
    PelicanoControlJNI.PelicanoClass_ErrorNoSolved_set(swigCPtr, this, value);
  }

  public boolean getErrorNoSolved() {
    return PelicanoControlJNI.PelicanoClass_ErrorNoSolved_get(swigCPtr, this);
  }

  public void setErrorOCode(int value) {
    PelicanoControlJNI.PelicanoClass_ErrorOCode_set(swigCPtr, this, value);
  }

  public int getErrorOCode() {
    return PelicanoControlJNI.PelicanoClass_ErrorOCode_get(swigCPtr, this);
  }

  public void setErrorOMsg(String value) {
    PelicanoControlJNI.PelicanoClass_ErrorOMsg_set(swigCPtr, this, value);
  }

  public String getErrorOMsg() {
    return PelicanoControlJNI.PelicanoClass_ErrorOMsg_get(swigCPtr, this);
  }

  public void setErrorOStatic(int value) {
    PelicanoControlJNI.PelicanoClass_ErrorOStatic_set(swigCPtr, this, value);
  }

  public int getErrorOStatic() {
    return PelicanoControlJNI.PelicanoClass_ErrorOStatic_get(swigCPtr, this);
  }

  public void setErrorOCritical(int value) {
    PelicanoControlJNI.PelicanoClass_ErrorOCritical_set(swigCPtr, this, value);
  }

  public int getErrorOCritical() {
    return PelicanoControlJNI.PelicanoClass_ErrorOCritical_get(swigCPtr, this);
  }

  public void setFaultOCode(int value) {
    PelicanoControlJNI.PelicanoClass_FaultOCode_set(swigCPtr, this, value);
  }

  public int getFaultOCode() {
    return PelicanoControlJNI.PelicanoClass_FaultOCode_get(swigCPtr, this);
  }

  public void setFaultOMsg(String value) {
    PelicanoControlJNI.PelicanoClass_FaultOMsg_set(swigCPtr, this, value);
  }

  public String getFaultOMsg() {
    return PelicanoControlJNI.PelicanoClass_FaultOMsg_get(swigCPtr, this);
  }

  public void setCoinPresent(boolean value) {
    PelicanoControlJNI.PelicanoClass_CoinPresent_set(swigCPtr, this, value);
  }

  public boolean getCoinPresent() {
    return PelicanoControlJNI.PelicanoClass_CoinPresent_get(swigCPtr, this);
  }

  public void setTrashDoorOpen(boolean value) {
    PelicanoControlJNI.PelicanoClass_TrashDoorOpen_set(swigCPtr, this, value);
  }

  public boolean getTrashDoorOpen() {
    return PelicanoControlJNI.PelicanoClass_TrashDoorOpen_get(swigCPtr, this);
  }

  public void setLowerSensorBlocked(boolean value) {
    PelicanoControlJNI.PelicanoClass_LowerSensorBlocked_set(swigCPtr, this, value);
  }

  public boolean getLowerSensorBlocked() {
    return PelicanoControlJNI.PelicanoClass_LowerSensorBlocked_get(swigCPtr, this);
  }

  public void setUpperSensorBlocked(boolean value) {
    PelicanoControlJNI.PelicanoClass_UpperSensorBlocked_set(swigCPtr, this, value);
  }

  public boolean getUpperSensorBlocked() {
    return PelicanoControlJNI.PelicanoClass_UpperSensorBlocked_get(swigCPtr, this);
  }

  public void setActOCoin(int value) {
    PelicanoControlJNI.PelicanoClass_ActOCoin_set(swigCPtr, this, value);
  }

  public int getActOCoin() {
    return PelicanoControlJNI.PelicanoClass_ActOCoin_get(swigCPtr, this);
  }

  public void setActOChannel(int value) {
    PelicanoControlJNI.PelicanoClass_ActOChannel_set(swigCPtr, this, value);
  }

  public int getActOChannel() {
    return PelicanoControlJNI.PelicanoClass_ActOChannel_get(swigCPtr, this);
  }

  public void setActualSpeed(int value) {
    PelicanoControlJNI.PelicanoClass_ActualSpeed_set(swigCPtr, this, value);
  }

  public int getActualSpeed() {
    return PelicanoControlJNI.PelicanoClass_ActualSpeed_get(swigCPtr, this);
  }

  public void setTotalInsertionCounter(long value) {
    PelicanoControlJNI.PelicanoClass_TotalInsertionCounter_set(swigCPtr, this, value);
  }

  public long getTotalInsertionCounter() {
    return PelicanoControlJNI.PelicanoClass_TotalInsertionCounter_get(swigCPtr, this);
  }

  public void setLoggerLevel(int value) {
    PelicanoControlJNI.PelicanoClass_LoggerLevel_set(swigCPtr, this, value);
  }

  public int getLoggerLevel() {
    return PelicanoControlJNI.PelicanoClass_LoggerLevel_get(swigCPtr, this);
  }

  public void setLogFilePath(String value) {
    PelicanoControlJNI.PelicanoClass_LogFilePath_set(swigCPtr, this, value);
  }

  public String getLogFilePath() {
    return PelicanoControlJNI.PelicanoClass_LogFilePath_get(swigCPtr, this);
  }

  public void setMaxPorts(int value) {
    PelicanoControlJNI.PelicanoClass_MaxPorts_set(swigCPtr, this, value);
  }

  public int getMaxPorts() {
    return PelicanoControlJNI.PelicanoClass_MaxPorts_get(swigCPtr, this);
  }

  public PelicanoClass() {
    this(PelicanoControlJNI.new_PelicanoClass(), true);
  }

  public SpdlogLevels_t SearchSpdlogLevel(int Code) {
    return new SpdlogLevels_t(PelicanoControlJNI.PelicanoClass_SearchSpdlogLevel(swigCPtr, this, Code), true);
  }

  public void SetSpdlogLevel() {
    PelicanoControlJNI.PelicanoClass_SetSpdlogLevel(swigCPtr, this);
  }

  public ErrorCodeExComm_t SearchErrorCodeExComm(int Code) {
    return new ErrorCodeExComm_t(PelicanoControlJNI.PelicanoClass_SearchErrorCodeExComm(swigCPtr, this, Code), true);
  }

  public CoinPolling_t SearchCoin(int Channel) {
    return new CoinPolling_t(PelicanoControlJNI.PelicanoClass_SearchCoin(swigCPtr, this, Channel), true);
  }

  public ErrorCodePolling_t SearchErrorCodePolling(int Code) {
    return new ErrorCodePolling_t(PelicanoControlJNI.PelicanoClass_SearchErrorCodePolling(swigCPtr, this, Code), true);
  }

  public FaultCode_t SearchFaultCode(int Code) {
    return new FaultCode_t(PelicanoControlJNI.PelicanoClass_SearchFaultCode(swigCPtr, this, Code), true);
  }

  public int StIdle() {
    return PelicanoControlJNI.PelicanoClass_StIdle(swigCPtr, this);
  }

  public int StConnect() {
    return PelicanoControlJNI.PelicanoClass_StConnect(swigCPtr, this);
  }

  public int StCheck() {
    return PelicanoControlJNI.PelicanoClass_StCheck(swigCPtr, this);
  }

  public int StEnable() {
    return PelicanoControlJNI.PelicanoClass_StEnable(swigCPtr, this);
  }

  public int StPolling() {
    return PelicanoControlJNI.PelicanoClass_StPolling(swigCPtr, this);
  }

  public int StCleanBowl() {
    return PelicanoControlJNI.PelicanoClass_StCleanBowl(swigCPtr, this);
  }

  public int StReset() {
    return PelicanoControlJNI.PelicanoClass_StReset(swigCPtr, this);
  }

  public int StError() {
    return PelicanoControlJNI.PelicanoClass_StError(swigCPtr, this);
  }

  public void InitLogger(String Path) {
    PelicanoControlJNI.PelicanoClass_InitLogger(swigCPtr, this, Path);
  }

  public int ConnectSerial(int Port) {
    return PelicanoControlJNI.PelicanoClass_ConnectSerial(swigCPtr, this, Port);
  }

  public int ScanPorts() {
    return PelicanoControlJNI.PelicanoClass_ScanPorts(swigCPtr, this);
  }

  public int SendingCommand(SWIGTYPE_p_std__vectorT_unsigned_char_t Comm) {
    return PelicanoControlJNI.PelicanoClass_SendingCommand(swigCPtr, this, SWIGTYPE_p_std__vectorT_unsigned_char_t.getCPtr(Comm));
  }

  public int ExecuteCommand(SWIGTYPE_p_std__vectorT_unsigned_char_t Comm) {
    return PelicanoControlJNI.PelicanoClass_ExecuteCommand(swigCPtr, this, SWIGTYPE_p_std__vectorT_unsigned_char_t.getCPtr(Comm));
  }

  public int HandleResponse(SWIGTYPE_p_std__vectorT_unsigned_char_t Response, int Rdlen, int Xlen) {
    return PelicanoControlJNI.PelicanoClass_HandleResponse(swigCPtr, this, SWIGTYPE_p_std__vectorT_unsigned_char_t.getCPtr(Response), Rdlen, Xlen);
  }

  public int HandleResponsePolling(SWIGTYPE_p_std__vectorT_unsigned_char_t Response, int Rdlen) {
    return PelicanoControlJNI.PelicanoClass_HandleResponsePolling(swigCPtr, this, SWIGTYPE_p_std__vectorT_unsigned_char_t.getCPtr(Response), Rdlen);
  }

  public int HandleResponseInfo(SWIGTYPE_p_std__vectorT_unsigned_char_t Response, int Rdlen) {
    return PelicanoControlJNI.PelicanoClass_HandleResponseInfo(swigCPtr, this, SWIGTYPE_p_std__vectorT_unsigned_char_t.getCPtr(Response), Rdlen);
  }

  public int CheckOptoStates() {
    return PelicanoControlJNI.PelicanoClass_CheckOptoStates(swigCPtr, this);
  }

  public int SimplePoll() {
    return PelicanoControlJNI.PelicanoClass_SimplePoll(swigCPtr, this);
  }

  public int SelfCheck() {
    return PelicanoControlJNI.PelicanoClass_SelfCheck(swigCPtr, this);
  }

  public int EnableChannels() {
    return PelicanoControlJNI.PelicanoClass_EnableChannels(swigCPtr, this);
  }

  public int StartMotor() {
    return PelicanoControlJNI.PelicanoClass_StartMotor(swigCPtr, this);
  }

  public int CheckEventReset() {
    return PelicanoControlJNI.PelicanoClass_CheckEventReset(swigCPtr, this);
  }

  public int CleanBowl() {
    return PelicanoControlJNI.PelicanoClass_CleanBowl(swigCPtr, this);
  }

  public int StopMotor() {
    return PelicanoControlJNI.PelicanoClass_StopMotor(swigCPtr, this);
  }

  public int ResetDevice() {
    return PelicanoControlJNI.PelicanoClass_ResetDevice(swigCPtr, this);
  }

  public int SetSpeed(int cps) {
    return PelicanoControlJNI.PelicanoClass_SetSpeed(swigCPtr, this, cps);
  }

  public int GetSpeed() {
    return PelicanoControlJNI.PelicanoClass_GetSpeed(swigCPtr, this);
  }

  public int GetCountCoins() {
    return PelicanoControlJNI.PelicanoClass_GetCountCoins(swigCPtr, this);
  }

  public SWIGTYPE_p_std__vectorT_unsigned_char_t BuildCmdModifyInhibit(int InhibitMask1, int InhibitMask2) {
    return new SWIGTYPE_p_std__vectorT_unsigned_char_t(PelicanoControlJNI.PelicanoClass_BuildCmdModifyInhibit(swigCPtr, this, InhibitMask1, InhibitMask2), true);
  }

  public int ChangeInhibitChannels(int InhibitMask1, int InhibitMask2) {
    return PelicanoControlJNI.PelicanoClass_ChangeInhibitChannels(swigCPtr, this, InhibitMask1, InhibitMask2);
  }

}
